var metre = 10; //pixels
var numOfNodes = 40;
var nominalStringLength = 10;
var springConstant = 100;
var velocityDampingConstant = 2;
var viscousConstant = 0.4;
var running = true;
var simulationSpeed = 3; // times real time
var maxStep = 10;  // milliseconds
var dangerForceMax = 300;
var dangerForceMin = 200;